"""Build the MEMMAP helper; --check verifies previously generated bytes."""
import argparse
from pathlib import Path
import subprocess
import tempfile

root = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser()
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
with tempfile.TemporaryDirectory() as directory:
    obj, binary = Path(directory) / 'helper.o', Path(directory) / 'helper.bin'
    subprocess.run(['arm-none-eabi-gcc', '-mcpu=cortex-m3', '-mthumb', '-c', str(root / 'tools/flash-map.S'), '-o', str(obj)], check=True)
    subprocess.run(['arm-none-eabi-objcopy', '-O', 'binary', '-j', '.text', str(obj), str(binary)], check=True)
    data = binary.read_bytes()
    result = '// Generated by tools/build_helper.py from tools/flash-map.S.\n'
    result += 'export const FLASH_MAP_HELPER = new Uint8Array([' + ', '.join(f'0x{b:02x}' for b in data) + ']);\n'
    target = root / 'src/generated/flash-map.ts'
    target.parent.mkdir(parents=True, exist_ok=True)
    if args.check:
        if target.read_text() != result:
            raise SystemExit('Helper bytes differ; run python3 tools/build_helper.py')
        print(f'Helper matches assembly ({len(data)} bytes).')
    else:
        target.write_text(result)
